In [1]:
from src.api import getHistoricoMOW
from src.utils import isValidCode, parallelizeFunction, parseDate, rellenarId
import pandas as pd
import numpy as np
from datetime import timedelta
from src.utils.topos import loadElementosTopos
from src.api.api import GraylogAPIProcessor
from src.processor import SitraProcessor
from datetime import datetime
from pathlib import Path
import csv
from src.utils.timeformat import formatTimedelta
from src.utils import (
    formatTimedelta,
    guardarExcel,
    isValidCode,
    rellenarId,
    time2localtime,
    guardarExcelMulti
)
from src.utils.util import loadEstaciones

In [ ]:



graylock = GraylogAPIProcessor()
today_str = (datetime.now() - timedelta(days=1)).strftime("%Y%m%d")
fname = Path(r"C:\Users\xiangzhou.zhang\Documents\Data\graylog\sitra")/ f"{today_str}_Sitra.txt"
response = graylock.saveResponse(fname,"02-07-2025","02-07-2025",[],"sitra")
output_csv = str(Path(fname).with_suffix('.csv'))
with open(fname, 'r', encoding='utf-8') as txtfile, \
     open(output_csv, 'w', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(txtfile, delimiter=',')
    writer = csv.writer(csvfile)
    for row in reader:
        writer.writerow(row)

In [2]:
sitraproceso = SitraProcessor()
today_str = (datetime.now() - timedelta(days=1)).strftime("%Y%m%d")
# fname_sitra=Path(r"c:\Users\xiangzhou.zhang\Documents\Data\graylog\sitra")/ f"{today_str}_sitra.csv"
# fname_ru = Path(r"c:\Users\xiangzhou.zhang\Documents\Data\graylog\sitra\20250616_ruOperation.csv")
fname_sitra= Path(r"c:\Users\xiangzhou.zhang\Downloads\graylog-search-result-absolute-2025-09-13T22_00_00.000Z-2025-09-14T22_00_00.000Z.csv")
log_rm = sitraproceso.readLogFile(fname_sitra)
df_rm = sitraproceso.loadRealMovement(log_rm)
# df_rp = sitraproceso.loadRealParking(log_rm)

Formateando fechas.:   0%|          | 0/1 [00:00<?, ?it/s]

Formateando fechas.:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
rm=df_rm[df_rm["NTécnico"] == "02151"]

In [ ]:
rp =df_rp[df_rp["NTécnico"] =="02151"]

In [ ]:
data= {
    "Realmovement":rm,
    "RealParking": rp
}

In [ ]:
fname = Path(r"C:\Users\xiangzhou.zhang\Documents\Data\Informe_puntual\tren_02151.xlsx")

In [ ]:
guardarExcelMulti(data,fname)

In [3]:
df_supresión =  df_rm[df_rm["Movimiento"] == "SUPRESIÓN"]

In [5]:
def int_to_hms(valor):
    valor = int(valor)
    h = valor // 10000
    m = (valor % 10000) // 100
    s = valor % 100
    return f"{h:02d}:{m:02d}:{s:02d}"

In [6]:
df_supresión1 = df_supresión.copy()
df_supresión1["HoraPlanificada"] = df_supresión1["HoraPlanificada"].astype(int)
df_supresión1["HoraPlanificada"] = df_supresión1["HoraPlanificada"].apply(int_to_hms)

In [7]:
df_supresión1["Fecha"] = pd.to_datetime(df_supresión1["Fecha"])
df_supresión1["HoraPlanificada"] = pd.to_datetime(
    df_supresión1["Fecha"].dt.strftime("%Y-%m-%d") + " " + df_supresión1["HoraPlanificada"],
    format="%Y-%m-%d %H:%M:%S"
)

In [8]:
df_supresión1

,FechaOrigen,NTécnico,Código,Secuencia,RetrasoLlegada,RetrasoSalida,HoraPlanificada,Fecha,FechaESB,Movimiento,Fuente,CodigoRetrasoLlegada,CodigoRetrasoSalida,Nombre,Retraso
139,2025-09-13,75870,17000,12,9,9,2025-09-14 23:21:00,2025-09-14 00:01:28,2025-09-14 00:01:28,SUPRESIÓN,Manual,XXX,M85,Madrid Chamartín Clara Campoamor,0 days 00:09:00
145,2025-09-13,27510,17000,7,4,4,2025-09-14 00:01:00,2025-09-14 00:08:37,2025-09-14 00:08:37,SUPRESIÓN,Manual,D55,M85,Madrid Chamartín Clara Campoamor,0 days 00:04:00
147,2025-09-13,27315,18000,12,-1,-1,2025-09-14 23:59:00,2025-09-14 00:09:49,2025-09-14 00:09:49,SUPRESIÓN,Manual,None,M85,Madrid Atocha Cercanías,-1 days +23:59:00
105,2025-09-13,27510,17000,7,5,5,2025-09-14 00:01:00,2025-09-14 00:15:31,2025-09-14 00:15:31,SUPRESIÓN,Manual,XXX,M85,Madrid Chamartín Clara Campoamor,0 days 00:05:00
172,2025-09-14,39107,18000,1,0,0,2025-09-14 00:29:00,2025-09-14 00:23:14,2025-09-14 00:23:14,SUPRESIÓN,Manual,None,M80,Madrid Atocha Cercanías,0 days 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,2025-09-14,64203,60101,66,113,113,2025-09-14 21:58:50,2025-09-14 23:48:29,2025-09-14 23:48:29,SUPRESIÓN,Manual,None,M85,San Cristóbal Industrial,0 days 01:53:00
167,2025-09-14,37023,17000,1,0,0,2025-09-14 23:57:00,2025-09-14 23:49:15,2025-09-14 23:49:16,SUPRESIÓN,Manual,None,M00,Madrid Chamartín Clara Campoamor,0 days 00:00:00
176,2025-09-15,97882,02005,1,0,0,2025-09-14 00:01:00,2025-09-14 23:50:43,2025-09-14 23:50:43,SUPRESIÓN,Manual,None,M80,Los Prados-A.V.,0 days 00:00:00
197,2025-09-15,93677,51407,1,0,0,2025-09-14 00:01:00,2025-09-14 23:54:58,2025-09-14 23:54:58,SUPRESIÓN,Manual,None,M00,Cortadura,0 days 00:00:00
212,2025-09-14,75870,18002,13,16,16,2025-09-14 23:26:30,2025-09-14 23:55:22,2025-09-14 23:55:22,SUPRESIÓN,Manual,None,M85,Madrid Nuevos Ministerios,0 days 00:16:00

In [9]:
df_supresión1["Anticipación"] = df_supresión1["HoraPlanificada"] - df_supresión1["Fecha"]

In [10]:
df_supresión1["Fecha"] =pd.to_datetime(df_supresión1["Fecha"])
df_supresión1["HoraPlanificada"] = pd.to_datetime(df_supresión1["HoraPlanificada"])
df_supresión1["Anticipación"] = df_supresión1["HoraPlanificada"] - df_supresión1["Fecha"]

In [11]:
df_supresión1["Anticipación"] = df_supresión1["Anticipación"].apply(lambda x: formatTimedelta(x.total_seconds()))

In [13]:
df_supresión1

,FechaOrigen,NTécnico,Código,Secuencia,RetrasoLlegada,RetrasoSalida,HoraPlanificada,Fecha,FechaESB,Movimiento,Fuente,CodigoRetrasoLlegada,CodigoRetrasoSalida,Nombre,Retraso,Anticipación
159197,2025-07-07,38612,71801,1,0,0,2025-07-07 00:01:00,2025-07-07 00:00:07,2025-07-07 00:00:07,SUPRESIÓN,Manual,None,M80,Barcelona Sants,0 days 00:00:00,00:00:53
157698,2025-07-06,39814,71801,1,0,0,2025-07-07 23:50:00,2025-07-07 00:00:31,2025-07-07 00:00:31,SUPRESIÓN,Manual,None,M86,Barcelona Sants,0 days 00:00:00,23:49:29
160635,2025-07-06,97682,04107,7,17,17,2025-07-07 23:21:00,2025-07-07 00:03:44,2025-07-07 00:03:44,SUPRESIÓN,Manual,None,M85,Vilafranca Del Penedes-A. V.,0 days 00:17:00,23:17:16
128684,2025-07-07,90230,04101,1,0,0,2025-07-07 01:08:00,2025-07-07 00:05:28,2025-07-07 00:05:28,SUPRESIÓN,Manual,None,M86,Les Borges Blanques-A. V.,0 days 00:00:00,01:02:32
161530,2025-07-07,97648,04101,1,0,0,2025-07-07 01:59:00,2025-07-07 00:06:07,2025-07-07 00:06:07,SUPRESIÓN,Manual,None,M86,Les Borges Blanques-A. V.,0 days 00:00:00,01:52:53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54923,2025-07-08,53309,43023,1,0,0,2025-07-07 04:55:00,2025-07-07 23:43:08,2025-07-07 23:43:08,SUPRESIÓN,Manual,None,M80,Huelva-Mercancias,0 days 00:00:00,-18:48:08
62412,2025-07-07,90224,65301,76,276,276,2025-07-07 19:06:40,2025-07-07 23:43:30,2025-07-07 23:43:30,SUPRESIÓN,Manual,XXX,M80,Les Palmes,0 days 04:36:00,-04:36:50
212870,2025-07-07,37017,17000,1,0,0,2025-07-07 22:36:00,2025-07-07 23:47:07,2025-07-07 23:47:07,SUPRESIÓN,Manual,None,M80,Madrid Chamartín Clara Campoamor,0 days 00:00:00,-01:11:07
206784,2025-07-07,91342,17000,1,0,0,2025-07-07 23:45:00,2025-07-07 23:54:50,2025-07-07 23:54:50,SUPRESIÓN,Manual,None,M86,Madrid Chamartín Clara Campoamor,0 days 00:00:00,-00:09:50
206733,2025-07-07,91342,17000,1,0,0,2025-07-07 23:45:00,2025-07-07 23:54:55,2025-07-07 23:54:55,SUPRESIÓN,Manual,None,M86,Madrid Chamartín Clara Campoamor,0 days 00:00:00,-00:09:55

In [14]:
df_supresión1 = df_supresión1.drop(columns=["CodigoRetrasoLlegada","CodigoRetrasoSalida","Nombre","Retraso","RetrasoLlegada","RetrasoSalida"])

In [15]:
df_supresión1

,FechaOrigen,NTécnico,Código,Secuencia,HoraPlanificada,Fecha,FechaESB,Movimiento,Fuente,Anticipación
159197,2025-07-07,38612,71801,1,2025-07-07 00:01:00,2025-07-07 00:00:07,2025-07-07 00:00:07,SUPRESIÓN,Manual,00:00:53
157698,2025-07-06,39814,71801,1,2025-07-07 23:50:00,2025-07-07 00:00:31,2025-07-07 00:00:31,SUPRESIÓN,Manual,23:49:29
160635,2025-07-06,97682,04107,7,2025-07-07 23:21:00,2025-07-07 00:03:44,2025-07-07 00:03:44,SUPRESIÓN,Manual,23:17:16
128684,2025-07-07,90230,04101,1,2025-07-07 01:08:00,2025-07-07 00:05:28,2025-07-07 00:05:28,SUPRESIÓN,Manual,01:02:32
161530,2025-07-07,97648,04101,1,2025-07-07 01:59:00,2025-07-07 00:06:07,2025-07-07 00:06:07,SUPRESIÓN,Manual,01:52:53
...,...,...,...,...,...,...,...,...,...,...
54923,2025-07-08,53309,43023,1,2025-07-07 04:55:00,2025-07-07 23:43:08,2025-07-07 23:43:08,SUPRESIÓN,Manual,-18:48:08
62412,2025-07-07,90224,65301,76,2025-07-07 19:06:40,2025-07-07 23:43:30,2025-07-07 23:43:30,SUPRESIÓN,Manual,-04:36:50
212870,2025-07-07,37017,17000,1,2025-07-07 22:36:00,2025-07-07 23:47:07,2025-07-07 23:47:07,SUPRESIÓN,Manual,-01:11:07
206784,2025-07-07,91342,17000,1,2025-07-07 23:45:00,2025-07-07 23:54:50,2025-07-07 23:54:50,SUPRESIÓN,Manual,-00:09:50
206733,2025-07-07,91342,17000,1,2025-07-07 23:45:00,2025-07-07 23:54:55,2025-07-07 23:54:55,SUPRESIÓN,Manual,-00:09:55

In [16]:
rename_columns = {
    "FechaOrigen": "FechaOrigen de la circulación",
    "NTécnico": "NTécnico",
    # "Código": "Código estación donde se surpime",
    "Secuencia":"Secuencia",
    "HoraPlanificada":"HoraPlanificada de salida del tren",
    "Fecha":"Fecha y hora anuncio supresión",
    "Movimiento":"Movimiento",
    "Anticipación":"Anticipación con la que se realiza la supresión"
}

In [17]:
df_supresión1.rename(columns=rename_columns,inplace=True)

In [18]:
df_supresión1.drop(columns=["FechaESB", "Fuente"],inplace=True)

In [19]:
df_supresión1.reset_index(drop=True,inplace=True)

In [20]:
topo = loadEstaciones()

In [21]:
topo = topo[["Código","Nombre"]]
topo.drop_duplicates(subset=["Código"], inplace=True)

In [22]:
conteo = df_supresión.groupby("Código")["NTécnico"].nunique().reset_index(name="trenes_suprimidos")

In [23]:
conteo = pd.merge(
    conteo,
    topo,
    on = ["Código"],
    how= "left"
)

In [24]:
conteo = conteo[["Código","Nombre","trenes_suprimidos"]]

In [25]:
conteo

    Código                  Nombre  trenes_suprimidos
0    02003     Antequera-Santa Ana                  3
1    02005              Los Prados                  1
2    04040       Zaragoza-Delicias                  2
3    04054               Vallmanya                  3
4    04101  Les Borges Blanques AV                  3
..     ...                     ...                ...
183  A1510                     NaN                  3
184  B3730                     NaN                  1
185  B7900             Bif.Sagrera                  1
186  B9701                     NaN                  1
187  C1160                     NaN                  1

[188 rows x 3 columns]

In [26]:
def hms_to_seconds(hms):
    h, m, s = map(int, hms.split(":"))
    return h * 3600 + m * 60 + s

In [27]:
df_supresión1["Anticipacion_seg"] = df_supresión1["Anticipación con la que se realiza la supresión"].apply(
    lambda x: hms_to_seconds(x) if not x.startswith('-') else 0
)

In [28]:
df_filtrado = df_supresión1[df_supresión1["Anticipacion_seg"] > 300]

In [29]:
conteo_mas_5min = df_filtrado.groupby("Código")["NTécnico"].count().reset_index(name="Anticipación mayor que 5min")

In [30]:
df_filtrado = df_supresión1[(df_supresión1["Anticipacion_seg"] > 0) & (df_supresión1["Anticipacion_seg"] < 300)]

In [31]:
conteo_menos_5min = df_filtrado.groupby("Código")["NTécnico"].count().reset_index(name="Anticipación menor que 5min")

In [32]:
df_filtrado = df_supresión1[(df_supresión1["Anticipacion_seg"] == 0)]

In [33]:
conteo_sin_anti = df_filtrado.groupby("Código")["NTécnico"].count().reset_index(name="Sin anticipación")

In [34]:
conteo = pd.merge(
    conteo,
    conteo_mas_5min,
    on = ["Código"],
    how = "left"
)

In [35]:
conteo = pd.merge(
    conteo,
    conteo_menos_5min,
    on = ["Código"],
    how = "left"
)
conteo = pd.merge(
    conteo,
    conteo_sin_anti,
    on = ["Código"],
    how = "left"
)

In [36]:
topo[topo["Código"] == "04040"]

     Código             Nombre
1323  04040  Zaragoza-Delicias

In [37]:
conteo

,Código,Nombre,trenes_suprimidos,Anticipación mayor que 5min,Anticipación menor que 5min,Sin anticipación
0,02003,Antequera-Santa Ana,3,3.0,NaN,NaN
1,02005,Los Prados,1,NaN,NaN,1.0
2,04040,Zaragoza-Delicias,2,1.0,NaN,1.0
3,04054,Vallmanya,3,3.0,NaN,NaN
4,04101,Les Borges Blanques AV,3,4.0,NaN,NaN
...,...,...,...,...,...,...
183,A1510,NaN,3,6.0,NaN,NaN
184,B3730,NaN,1,1.0,NaN,NaN
185,B7900,Bif.Sagrera,1,NaN,NaN,1.0
186,B9701,NaN,1,1.0,NaN,NaN
187,C1160,NaN,1,1.0,NaN,NaN

In [38]:
fname = Path(r"C:\Users\xiangzhou.zhang\Documents\Data\Informe\anticipacion\Anticipación_20250707.xlsx")

In [39]:
data = {"Resumen":conteo,"Detalle":df_supresión1}

In [40]:
guardarExcelMulti(data,fname)

Guardando: Resumen (1/2)
Guardando: Detalle (2/2)